examples:
- txtar: |2

    -- nginx.yml --
    ---
    - hosts: localhost
      connection: local
      become: true

      tasks:
        - name: Install nginx
          ansible.builtin.package:
            name: nginx
            state: present
    -- run --
    ansible-playbook nginx.yml
